### ISSUE TITLE
PyFlume Potentially Not Returning Data

### ISSUE THREAD

**Issue by gbdesai2004** [ChrisMandich/PyFlume#7]
So a bit over 48 hours ago my Flume integration stopped reporting anything but 0 water usage.  It is creating a token file and isn't throwing log errors, but again it's not returning any usage data.  It's also not reporting unavailable, just 0.

I have deleted and re-added the integration in HA.  I have deleted the token file and restarted HA to recreate it.  I have examined the HA logs (nothing found).  I have confirmed the API is still active on the Flume side.  I was using 0.112 when I first saw the problem.  I have since upgraded to 0.113 but still see the same issue.

I have contacted Flume and Henry, one of their engineers, tested the API on his side and said it seems to be working properly.  He requested an actual post body to see if something may be off there.  I suppose I'd have to figure a way to capture the post content do provide what he needs. 

Seems there is at least one other person with the issue.  Here is the thread where I was discussing the issue.

https://community.home-assistant.io/t/flume-water-meter/124485/94?u=gbdesai

I installed PyFlume on it's own, set it up and used the sample code provided to pull some data from the API...

```
DEVICE LIST
[ redacted, but I had plenty of data in here starting with the DEVICE ID]
DEVICE ID
6557xxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "check.py", line 33, in <module>
    flume = pyflume.FlumeData(
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 360, in __init__
    self.update()
  File "/usr/local/lib/python3.8/dist-packages/ratelimit-2.2.1-py3.8.egg/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
  File "/usr/local/lib/python3.8/dist-packages/ratelimit-2.2.1-py3.8.egg/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 366, in update
    return self.update_force()
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 393, in update_force
    self.values = {k: responses[k][0]["value"] for k in self._query_keys}
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 393, in <dictcomp>
    self.values = {k: responses[k][0]["value"] for k in self._query_keys}
IndexError: list index out of range

```

So the flume = pyflume.FlumeData seems to fail for some reason.  

Any suggestions would be welcome.  Thanks.

G

**Comment by ChrisMandich** [comment]
Very interesting, when testing just the package I get no results as well. 
Here is the payload I tested with and the output received. 
I believe this might be on the flume side as I definitely should be seeing results for today. 

```****************************************
****************************************
QUERY PAYLOAD
****************************************
****************************************
{'queries': [{'request_id': 'current_interval', 'bucket': 'MIN', 'since_datetime': '2020-07-23 11:48:12', 'until_datetime': '2020-07-23 12:48:00', 'operation': 'SUM', 'units': 'GALLONS'}, {'request_id': 'current_min', 'bucket': 'MIN', 'since_datetime': '2020-07-23 12:48:12', 'operation': 'SUM', 'units': 'GALLONS'}, {'request_id': 'today', 'bucket': 'DAY', 'since_datetime': '2020-07-23 00:00:00', 'until_datetime': '2020-07-23 12:48:12', 'operation': 'SUM', 'units': 'GALLONS'}, {'request_id': 'week_to_date', 'bucket': 'DAY', 'since_datetime': '2020-07-20 00:00:00', 'until_datetime': '2020-07-23 12:48:12', 'operation': 'SUM', 'units': 'GALLONS'}, {'request_id': 'month_to_date', 'bucket': 'MON', 'since_datetime': '2020-07-01 00:00:00', 'until_datetime': '2020-07-23 12:48:12', 'units': 'GALLONS'}, {'request_id': 'last_60_min', 'bucket': 'MIN', 'since_datetime': '2020-07-23 11:48:12', 'until_datetime': '2020-07-23 12:48:12', 'operation': 'SUM', 'units': 'GALLONS'}, {'request_id': 'last_24_hrs', 'bucket': 'HR', 'since_datetime': '2020-07-22 12:48:12', 'until_datetime': '2020-07-23 12:48:12', 'operation': 'SUM', 'units': 'GALLONS'}, {'request_id': 'last_30_days', 'bucket': 'DAY', 'since_datetime': '2020-06-23 12:48:12', 'until_datetime': '2020-07-23 12:48:12', 'operation': 'SUM', 'units': 'GALLONS'}]}


****************************************
****************************************
FLUME VALUES
****************************************
****************************************
{'current_interval': 0, 'current_min': 0, 'today': 0, 'week_to_date': 0, 'month_to_date': 8891.97237344, 'last_60_min': 0, 'last_24_hrs': 0, 'last_30_days': 12330.11111072}
****************************************
****************************************
```

**Comment by ChrisMandich** [comment]
Logging into the console also returned no results https://portal.flumewater.com/dashboard
Can you validate if your dashboard returns anything within the last 24-hours?  @gbdesai2004

**Comment by joe248** [comment]
I have this issue as well.  No data for the past 2 days or so.

**Comment by gbdesai2004** [comment]
> Logging into the console also returned no results https://portal.flumewater.com/dashboard
> Can you validate if your dashboard returns anything within the last 24-hours? @gbdesai2004

Mine does. Seems accurate to the minute.

**Comment by gbdesai2004** [comment]
Sorry on mobile but wrong button

**Comment by ChrisMandich** [comment]
@joe248, in the flume data dashboard are you receiving anything? Mine stopped populating 07/16 reaching out to support on this...

**Comment by ChrisMandich** [comment]
Reached out to Flume support and they reported an error with my device and are shipping me a replacement. I'll work on integrating the latest PyFlume package to HA. The latest one is working with the API, feel free to test the API with this script.
```
import pyflume
import logging
from datetime import timedelta
from requests import Session

logging.basicConfig(filename="flume.log",level=logging.DEBUG)

KEY_DEVICE_TYPE = "type"
KEY_DEVICE_ID = "id"
FLUME_TYPE_SENSOR = 2

username="username"
password="password"
client_id="client_id"
client_secret="secret"

SCAN_INTERVAL = timedelta(minutes=60)

auth = pyflume.FlumeAuth(
        username, password, client_id, client_secret, http_session=Session()
        )

flume_devices = pyflume.FlumeDeviceList(auth)
devices = flume_devices.get_devices()

print()
print()
print("*" * 40)
print("*" * 40)
print("DEVICE LIST")
print("*" * 40)
print("*" * 40)
print(devices)

print()
print()
print("*" * 40)
print("*" * 40)
print("DEVICE ID")
print("*" * 40)
print("*" * 40)
for device in flume_devices.device_list:
    if device[KEY_DEVICE_TYPE] == FLUME_TYPE_SENSOR:
        print(device[KEY_DEVICE_ID])
        device_id = device[KEY_DEVICE_ID]

flume = pyflume.FlumeData(
            auth,
            device_id,
            SCAN_INTERVAL,
            http_session=Session(),
        )

flume_notifications = pyflume.FlumeNotificationList(auth, read="true")

print()
print()
print("*" * 40)
print("*" * 40)
print("NOTIFICATION LIST")
print("*" * 40)
print("*" * 40)
print(flume_notifications.notification_list)

flume.update_force()

print()
print()
print("*" * 40)
print("*" * 40)
print("AUTH HEADER")
print("*" * 40)
print("*" * 40)
print(auth.authorization_header)

print()
print()
print("*" * 40)
print("*" * 40)
print("QUERY PAYLOAD")
print("*" * 40)
print("*" * 40)
print(pyflume._generate_api_query_payload(SCAN_INTERVAL))

print()
print()
print("*" * 40)
print("*" * 40)
print("FLUME VALUES")
print("*" * 40)
print("*" * 40)
print(flume.values)
print("*" * 40)
print("*" * 40)

**Comment by gbdesai2004** [comment]
Assuming you need an "import pyflume" at the top of that... I ran it and still get an error.  Here is the output...

```
****************************************
****************************************
DEVICE LIST
****************************************
****************************************
[{'id': '655xxxxxxxxxxxxx', 'type': 2, 'bridge_id': '655xxxxxxxxxxxxxxxxxx', 'oriented': True, 'last_seen': '2020-07-23T22:00:43.000Z', 'connected': True, 'battery_level': 'high', 'product': 'flume1', 'user': {'id': xxxxx, 'email_address': 'xxxx', ...]


****************************************
****************************************
DEVICE ID
****************************************
****************************************
655xxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "checknew.py", line 44, in <module>
    flume = pyflume.FlumeData(
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 360, in __init__
    self.update()
  File "/usr/local/lib/python3.8/dist-packages/ratelimit-2.2.1-py3.8.egg/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
  File "/usr/local/lib/python3.8/dist-packages/ratelimit-2.2.1-py3.8.egg/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 366, in update
    return self.update_force()
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 393, in update_force
    self.values = {k: responses[k][0]["value"] for k in self._query_keys}
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 393, in <dictcomp>
    self.values = {k: responses[k][0]["value"] for k in self._query_keys}
IndexError: list index out of range
```

**Comment by ChrisMandich** [comment]
That's strange, I updated the script above to log to a debugging file called `flume.log` in the directory it is ran from. Can you execute the script again, strip the log file of any personal information and send it my way to review. 

Also, just for sanity can you provide the output of `pip show pyflume`

**Comment by joe248** [comment]
Yes, my dashboard is still populating in the Flume app

**Comment by gbdesai2004** [comment]
Ok, sounds good.  So here is the pip3 show pyflume results

```
Name: PyFlume
Version: 0.5.0
Summary: Package to integrate with Flume Sensor
Home-page: https://github.com/ChrisMandich/PyFlume
Author: ChrisMandich
Author-email: Chris@Mandich.net
License: UNKNOWN
Location: /usr/local/lib/python3.8/dist-packages/PyFlume-0.5.0-py3.8.egg
Requires: pyjwt, ratelimit
Required-by:
```
Also I ran it again just to be sure, even sudo'd and there is no log where I ran it.

Do I have the latest version per the above output?

UPDATE: Dumb, me I can't read.  Ok I updated the script, will run it and send you the log...

**Comment by gbdesai2004** [comment]
Ok, here is flume.log.  I did cleanse it of identifiable info.  I didn't see a way to send it to you as an email or attachment in PM.

[flume.log](https://github.com/ChrisMandich/PyFlume/files/4969617/flume.log)

Oh now I see your email address...  Anyway I still get the error I posted earlier in the console.  But obviously the debug shows usage data coming back.

```
****************************************
****************************************
DEVICE LIST
****************************************
****************************************
[{'id': '655ID1ID1ID1ID1ID1ID1', 'type': 2, 'bridge_id': '655ID2ID2ID2ID2ID2ID2', 'oriented': True, 'last_seen': '2020-07-23T23:26:08.000Z', 'connected': True, 'battery_level': 'high', 'product': 'flume1', 'user': {'id': 1XXX1, 'email_address': 'myemail@gmail.com', 'first_name': 'G', 'last_name': 'D', 'phone': '5555555555', 'status': 'Active', 'type': 'USER', 'signup_datetime': '2020-05-25T17:50:58.000Z'}, 'location': {'id': 1xxx9, 'user_id': 1XXX1, 'name': 'Bella Vista', 'primary_location': True, 'address': '101 My St', 'address_2': None, 'city': 'Diablo', 'state': 'CA', 'postal_code': '94528', 'country': 'United States', 'tz': 'America/Los_Angeles', 'installation': 'DONE', 'insurer_id': 21, 'building_type': 'SINGLE_FAMILY_HOME', 'away_mode': False, 'usage_profile': {'id': 3398, 'score': 24, 'residents': '4', 'bathrooms': '5+', 'irrigation': 'SPRINKLER_SYSTEM', 'irrigation_freq': '4+_PER_WEEK', 'irrigation_max_cycle': 360, 'has_pool': True}}}, {'id': '655ID2ID2ID2ID2ID2ID2', 'type': 1, 'bridge_id': None, 'last_seen': '2020-07-23T23:26:46.000Z', 'connected': True, 'supports_ap': True, 'product': 'flume1', 'user': {'id': 1XXX1, 'email_address': 'myemail@gmail.com', 'first_name': 'G', 'last_name': 'D', 'phone': '5555555555', 'status': 'Active', 'type': 'USER', 'signup_datetime': '2020-05-25T17:50:58.000Z'}, 'location': {'id': 1xxx9, 'user_id': 1XXX1, 'name': 'Bella Vista', 'primary_location': True, 'address': '101 My St', 'address_2': None, 'city': 'Diablo', 'state': 'CA', 'postal_code': '94528', 'country': 'United States', 'tz': 'America/Los_Angeles', 'installation': 'DONE', 'insurer_id': 21, 'building_type': 'SINGLE_FAMILY_HOME', 'away_mode': False, 'usage_profile': {'id': 3398, 'score': 24, 'residents': '4', 'bathrooms': '5+', 'irrigation': 'SPRINKLER_SYSTEM', 'irrigation_freq': '4+_PER_WEEK', 'irrigation_max_cycle': 360, 'has_pool': True}}}]


****************************************
****************************************
DEVICE ID
****************************************
****************************************
655ID1ID1ID1ID1ID1ID1
Traceback (most recent call last):
  File "checknew.py", line 47, in <module>
    flume = pyflume.FlumeData(
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 360, in __init__
    self.update()
  File "/usr/local/lib/python3.8/dist-packages/ratelimit-2.2.1-py3.8.egg/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
  File "/usr/local/lib/python3.8/dist-packages/ratelimit-2.2.1-py3.8.egg/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 366, in update
    return self.update_force()
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 393, in update_force
    self.values = {k: responses[k][0]["value"] for k in self._query_keys}
  File "/home/haadmin/pyflume/PyFlume/pyflume/__init__.py", line 393, in <dictcomp>
    self.values = {k: responses[k][0]["value"] for k in self._query_keys}
IndexError: list index out of range
````

**Comment by ChrisMandich** [comment]
Thanks for providing that, reviewing the log file I noticed that the result for `current_min` was not returning any data. This is causing the index out of range error. ```{'request_id': 'current_min', 'bucket': 'MIN', 'since_datetime': '2020-07-23 23:40:25', 'operation': 'SUM', 'units': 'GALLONS'}```. If I remove this request for the package it should resolve this error.

**Comment by ChrisMandich** [comment]
Updated it to check the length of the response. If there is no data in the response it does not return it. This change has been submitted to HA for review. https://github.com/home-assistant/core/pull/38138

**Comment by gbdesai2004** [comment]
Ok, this worked perfectly.  Thanks for much for making the updates!
